language: bash

before_install:
  - curl -sL https://deb.nodesource.com/setup_7.x | sudo -E bash -
  - sudo apt-get update
  - sudo apt-get install -y nodejs
  - sudo npm install -g grunt-cli
  - mvn -version
  - pwd
  - ls -lh 

script:
  - ./bin/build.sh
