dist: trusty
sudo: required
language: node_js

node_js:
  - "7"

services:
  - docker

before_install:
  - sudo add-apt-repository ppa:andrei-pozolotin/maven3
  - sudo apt-get -qq update
  - sudo apt-get install -y maven3
  - ant -version
  - mvn -version
  - pwd
  - ls -lh
  - sudo npm install -g grunt-cli
  - ./.build_travis.sh

script:
  - docker build -f docker-sarit-app/Dockerfile -t sarit-webapp .
