dist: trusty
sudo: false

services:
  - docker

before_install:
  # - docker pull patmcall/sarit-existdb:latest
  - docker build -f Dockerfile -t sarit-webapp .
  - docker run -d -p 127.0.0.1:8080:8080 --name sarit-existdb patmcall/sarit-existdb:latest
  - docker ps -a
  - until curl -s -o /dev/null "http://127.0.0.1:8080/exist/apps/sarit-pm/works/"; do echo "Wait for it ..."; sleep 2; done
  - docker ps -a

script:
  # more than one text?
  - curl "http://127.0.0.1:8080/exist/apps/sarit-pm/works/" | grep -E 'currently contains [1-9][0-9]+'
  # test search: iast in devnag text
  - curl "http://127.0.0.1:8080/exist/apps/sarit-pm/works/search.html?query=*pratyak%E1%B9%A3*&field=text&tei-target=tei-text&work-authors=all&target-texts=avayavinir%C4%81kara%E1%B9%87a" | grep -E '<span id="hit-count">[1-9]+</span>'
  # can we get an epub?
  - [ "$(curl -s 'http://127.0.0.1:8080/exist/apps/sarit-pm/works/asvaghosa-buddhacarita.epub?token=humptydumpty-super-secret-token&cache=no' | file -b -)" == "EPUB document" ]


# after_success:
#   - if [ "$TRAVIS_BRANCH" == "master" ]; then
#     docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
#     docker push patmcall/sarit-existdb;
#     fi
