dist: trusty
sudo: required
language: node_js

node_js:
  - "7"

services:
  - docker

before_install:
  - sudo apt-get -q update
  - sudo apt-get purge maven maven2 -y
  - sudo apt-get upgrade -y docker-engine
  - wget http://mirror.klaus-uwe.me/apache/maven/maven-3/3.5.0/binaries/apache-maven-3.5.0-bin.tar.gz
  - tar zxf apache-maven-3.5.0-bin.tar.gz
  - ant -version
  - ./apache-maven-3.5.0/bin/mvn --version
  - export M2_HOME=$PWD/apache-maven-3.5.0
  - export PATH=$M2_HOME/bin:$PATH
  - pwd
  - ls -lh
  - npm install -g npm@latest
  - npm install -g grunt-cli

script:
  - ./bin/build.sh
  - docker build -f Dockerfile -t sarit-webapp .


after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push patmcall/sarit-existdb;
    fi
