language: bash

before_install:
  - sudo apt-get update
  - sudo apt-get install -y --no-install-recommends ant npm maven
  - sudo npm install -g grunt-cli
  - mvn -version
  - pwd
  - ls -lh 

script:
  - ./bin/build.sh
